### ISSUE TITLE
关于scale的问题

### ISSUE THREAD

**Issue by badbubble** [pengshuang/Transformer#1]
https://github.com/pengshuang/Transformer/blob/b54ac12adccc45a28419504c26d65f51b3d1f5d0/util.py#L73-L81

key已经reshape了 scale 是不是该等于
```python
scale = key.size(-1) ** -0.5
```

**Comment by pengshuang** [comment]
谢谢，我重新看了下，确实不应该再除以 num_heads啦，bug已修改
