### ISSUE TITLE
`TypeError`  in PositionalEncoding

### ISSUE THREAD

**Issue by badbubble** [pengshuang/Transformer#3]
https://github.com/pengshuang/Transformer/blob/dd5829f9d7175ca2ef0d2e4e00f583a265d21849/util.py#L163-L164

len在这里是`torch.Tensor`类型的不能作为index使用的，会报错`TypeError: only integer tensors of a single element can be converted to an index`。

修改成这个就ok了，不知道用的对不对(Pytorch 初学者)
```python
input_pos = tensor(
            [list(range(1, int(len) + 1)) + [0] * (max_len - int(len)) for len in input_len])
```

**Comment by pengshuang** [comment]
fixed, thks!
