### ISSUE TITLE
关于mask的一点疑问

### ISSUE THREAD

**Issue by badbubble** [pengshuang/Transformer#5]
如果要计算encoder-decoder attention的padding mask，应该是将encoder的输出作为K和V，decoder第一个Multi-Head Attention的输出作为Q,然后将K和Q传入到`padding_mask`函数进行计算
https://github.com/pengshuang/Transformer/blob/dd5829f9d7175ca2ef0d2e4e00f583a265d21849/transformer.py#L29

我没理解错的话`context_attn_mask`在这里就是encoder-decoder attention的padding mask但却用了tgt_seq, src_seq作为输入,不能理解为什么这么计算。

我自己的想法是删掉这一行，修改DecoderLayer
```python
 def forward(self, dec_inputs, enc_outputs, self_attn_mask=None):
    dec_output, self_attention = self.attention(
        dec_inputs, dec_inputs, dec_inputs, self_attn_mask
    )
    #############
    context_attn_mask = padding_mask(enc_outputs, dec_output)
    #############
    dec_output, context_attention = self.attention(
        dec_output, enc_outputs, enc_outputs, context_attn_mask
    )

    dec_output = self.feed_forward(dec_output)

    return dec_output, self_attention, context_attention
```

**Comment by pengshuang** [comment]
首先，谢谢你看的这么仔细。
我是这么理解的。
这里我认为还是应该 tgt_seq, src_seq 作为输入。
因为在 seq2seq 模型中输入输出都会事先被padding成相同的长度，补齐的部分补0，我们这里的mask正是对补0的位置进行mask，如果这用输入变为 enc_outputs, dec_output， 这两个都是看出模型中间层的输出，它们是稠密的，不存在有0的位置，对它们进行mask也不会起到效果(**padding_mask** 函数并不会返回我们想要的mask)。

**Comment by badbubble** [comment]
@pengshuang 理解了，谢谢:smile:
